server:
  servlet:
    context-path: /migrator

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    embedded:
      version: 4.0.2
      storage:
        database-dir: "C:/Users/nacho/Development/azka/seguridata/migrator/mongo"