server:
  servlet:
    context-path: /migration

seguri-data:
  configs:
    links:

      - name: Facebook
        url: "https://facebook.com/SeguriDataMx/"
      - name: LinkedIn
        url: "https://linkedin.com/company/seguridata"
      - name: YouTube
        url: "https://youtube.com/channel/UCfvxNM-qv0j0rG1yldC67Yg"
      - name: X
        url: "https://x.com/seguridata"

spring:
  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    embedded:
      version: 4.0.2
      storage:
        database-dir: "C:/Users/nacho/Development/azka/seguridata/migrator/mongo"